name: Approve Request

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  issue_comment:
    types:
      - created

permissions: {}

concurrency:
  group: approve-request-${{ github.event.pull_request.number || github.event.issue.number || github.ref }}
  cancel-in-progress: true

jobs:
  approve:
    permissions:
      contents: read
      attestations: read
      issues: read
      pull-requests: read
    uses: civitaspo/securefix-server/.github/workflows/reusable-approve-request.yml@20f28eeb972c8961e799fb51c8b278ac1884ba8e # v0.1.0+20f28eeb972c8961e799fb51c8b278ac1884ba8e
    secrets:
      SECUREFIX_CLIENT_PRIVATE_KEY: ${{ secrets.SECUREFIX_CLIENT_PRIVATE_KEY }}
