name: Approve Request

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  issue_comment:
    types:
      - created

permissions: {}

concurrency:
  group: approve-request-${{ github.event.pull_request.number || github.event.issue.number || github.ref }}
  cancel-in-progress: true

jobs:
  approve:
    permissions:
      contents: read
      attestations: read
      issues: write
      pull-requests: read
    uses: civitaspo/securefix-server/.github/workflows/reusable-approve-request.yml@8cbf331b0698327bce6ac2ec50e6b1548e84e346 # v0.2.1
    secrets:
      SECUREFIX_CLIENT_PRIVATE_KEY: ${{ secrets.SECUREFIX_CLIENT_PRIVATE_KEY }}
