name: Merge Request

on:
  issue_comment:
    types:
      - created

permissions: {}

concurrency:
  group: merge-request-${{ github.event.comment.id }}
  cancel-in-progress: false

jobs:
  request:
    if: >-
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/merge') &&
      github.event.comment.user.id == 4525500 &&
      github.run_attempt == 1
    permissions:
      contents: read
      attestations: read
      issues: read
      pull-requests: read
    uses: civitaspo/securefix-server/.github/workflows/reusable-merge-request.yml@7716889a93e77c014b6332ffa46bc16b5a293a18 # v0.1.0+7716889a93e77c014b6332ffa46bc16b5a293a18
    secrets:
      SECUREFIX_CLIENT_PRIVATE_KEY: ${{ secrets.SECUREFIX_CLIENT_PRIVATE_KEY }}
