name: Policy Check

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  push:
    branches:
      - "main"

permissions: {}

concurrency:
  group: policy-check-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  check:
    permissions:
      actions: read
      contents: read
      attestations: read
      pull-requests: read
    uses: civitaspo/securefix-server/.github/workflows/reusable-policy-check.yml@800519353c2708774bd9db4b5210edbe11567efa # v0.2.0-pre.1
    secrets:
      SECUREFIX_CLIENT_PRIVATE_KEY: ${{ secrets.SECUREFIX_CLIENT_PRIVATE_KEY }}
