name: Pull Request Workflow

on:
  workflow_call:
    secrets:
      SECUREFIX_CLIENT_PRIVATE_KEY:
        required: false

permissions: {}

jobs:
  checks:
    uses: ./.github/workflows/workflow_call_pr.yml
    permissions:
      actions: read
      contents: read
      attestations: read
      pull-requests: read
    secrets:
      SECUREFIX_CLIENT_PRIVATE_KEY: ${{ secrets.SECUREFIX_CLIENT_PRIVATE_KEY }}
