name: Release PR Sync

on:
  push:
    branches:
      - release/next
  workflow_dispatch:

permissions: {}

concurrency:
  group: release-pr-sync
  cancel-in-progress: true

jobs:
  sync:
    permissions:
      contents: read
      attestations: read
      pull-requests: write
    uses: civitaspo/securefix-server/.github/workflows/reusable-release-pr-sync.yml@828616ad902793c4fec28bcf794b1e9a71549fff # v0.1.0+828616ad902793c4fec28bcf794b1e9a71549fff
