name: Release PR Sync

on:
  push:
    branches:
      - release/next
  workflow_dispatch:

permissions: {}

concurrency:
  group: release-pr-sync
  cancel-in-progress: true

jobs:
  sync:
    permissions:
      contents: read
      attestations: read
      pull-requests: write
    uses: civitaspo/securefix-server/.github/workflows/reusable-release-pr-sync.yml@800519353c2708774bd9db4b5210edbe11567efa # v0.2.0-pre.1
