name: Verify Securefix Server Candidate
on:
  workflow_dispatch:
permissions: {}
jobs:
  verify:
    permissions:
      actions: read
      contents: read
    uses: civitaspo/securefix-server/.github/workflows/testing-securefix-server.yml@97269f5fa9a686d1f130f08b000d1fae867dee55
    secrets:
      SECUREFIX_CLIENT_PRIVATE_KEY: ${{ secrets.SECUREFIX_CLIENT_PRIVATE_KEY }}
