name: Pull Request Checks (workflow_call)

on:
  workflow_call:
    secrets:
      SECUREFIX_CLIENT_PRIVATE_KEY:
        required: false

permissions: {}

jobs:
  autofix:
    uses: ./.github/workflows/wc-autofix.yml
    permissions:
      actions: read
      contents: read
      attestations: read
    secrets:
      SECUREFIX_CLIENT_PRIVATE_KEY: ${{ secrets.SECUREFIX_CLIENT_PRIVATE_KEY }}
